curl 'https://products.checkers.co.za/populateProductsWithHeavyAttributes' \
  -H 'accept: text/plain, */*; q=0.01' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json' \
  -b 'anonymous-consents=%5B%5D; checkersZA-preferredStore=57861; cookie-notification=NOT_ACCEPTED; webp_supported=true; JSESSIONID=Y1-c6531f8b-61d3-4654-a216-552449bb26ef; geolocation={%22latitude%22:-25.854112042833606%2C%22longitude%22:28.248802693574955%2C%22accuracy%22:61}; AWSALB=WaQLW/RwI3k23B6C2nmjpLA8nWH7eWZuhKI8bUzO05quIPvmPXnKiNxyhF1L8U0oQWhDqfi4ifi8dJaJIGMA5vZfHdxGfJ9tIus/5C0TYb7XfkXq7e4k/ngp6JGT; AWSALBCORS=WaQLW/RwI3k23B6C2nmjpLA8nWH7eWZuhKI8bUzO05quIPvmPXnKiNxyhF1L8U0oQWhDqfi4ifi8dJaJIGMA5vZfHdxGfJ9tIus/5C0TYb7XfkXq7e4k/ngp6JGT' \
  -H 'csrftoken: 9d37e264-9e63-4fcf-933c-d958161aef3a' \
  -H 'origin: https://products.checkers.co.za' \
  -H 'priority: u=1, i' \
  -H 'referer: https://products.checkers.co.za/c-2256/All-Departments?q=%3Arelevance%3AbrowseAllStoresFacetOff%3AbrowseAllStoresFacetOff%3AallCategories%3Afood' \
  -H 'sec-ch-ua: "Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36' \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw '[{"code":"10135941EA","price":{"value":32.99,"formattedValue":"R32.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10151456EA","price":{"value":2.99,"formattedValue":"R2.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10151458EA","price":{"value":2.99,"formattedValue":"R2.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10136301EA","price":{"value":19.99,"formattedValue":"R19.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10151065EA","price":{"value":19.99,"formattedValue":"R19.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10148833EA","price":{"value":19.99,"formattedValue":"R19.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10147193EA","price":{"value":39.99,"formattedValue":"R39.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10145817EA","price":{"value":16.99,"formattedValue":"R16.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10136298EA","price":{"value":17.99,"formattedValue":"R17.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10136574EA","price":{"value":17.99,"formattedValue":"R17.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10151462EA","price":{"value":3.49,"formattedValue":"R3.49","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10143000EA","price":{"value":36.99,"formattedValue":"R36.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10241929EA","price":{"value":19.99,"formattedValue":"R19.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10684677EA","price":{"value":19.99,"formattedValue":"R19.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10145422EA","price":{"value":29.99,"formattedValue":"R29.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10885550EA","price":{"value":15.99,"formattedValue":"R15.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10145033KG","price":{"value":19.99,"formattedValue":"R19.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10136291EA","price":{"value":12.99,"formattedValue":"R12.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10151458PK1","price":{"value":16.99,"formattedValue":"R16.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"},{"code":"10165121EA","price":{"value":21.99,"formattedValue":"R21.99","priceType":"BUY","currencyIso":"ZAR","promotionalPrice":false},"hasBabyCategory":"false"}]'

# Basically same as Shoprite

#categories:
 Food(7,748)
 Household(5,041)
 Food Cupboard(4,962)
 Drinks(4,052)
 Toiletries (3,154)
 Toys (1,913)
 Fresh Food (1,846)
 Gifts (1,737)
 Kitchen (1,537)
 Stationery & Newsagent (1,089)
 Cooking Ingredients (1,048)
 Wine (991)
 Party & Decorations (970)
 Cleaning (935)
 Chocolates & Sweets (838)
 Play Sets (771)
 Hair Care (678)
 Baby (644)
 Electronics (614)
 Outdoor (574)
 Frozen Food (554)
 Pets (508)
 Table Condiments & Dressings (470)
 Vitamins (464)
 Toddler Play Sets (441)
 Medicine (416)
 Plasticware (415)
 Red Wine (413)
 Spirits & Liqueurs (399)
 Juices & Smoothies (388)
 Biscuits, Cookies & Cereal Bars (374)
 Greeting Cards (367)
 Bakery (363)
 Chips, Snacks & Popcorn (357)
 Cheese (339)
 Bath, Shower & Soap (338)
 Coffee (307)
 Spirit Coolers (304)
 Fresh Meat & Poultry (298)
 Spirit & Wine Coolers (297)
 Wrapping & Gifting (296)
 Beer & Cider (288)
 Balloons (282)
 White Wine (282)
 Canned Food (279)
 Cars (273)
 Oral Care (269)
 Crockery (265)
 Cellphone & Tablet (264)
 Appliances (246)
 Breakfast Cereals, Porridge & Pap (244)
 Pet Food (239)
 Books (238)
 Biltong, Dried Fruit, Nuts & Seeds (235)
 Soft Drinks (233)
 Sports & Energy Drinks (225)
 Yoghurt (220)
 Tea (218)
 Dairy Drinks (215)
 Rice, Pasta, Noodles & Cous Cous (215)
 Birthday Greeting Cards (213)
 Baking (210)
 Beauty (210)
 Sanitary Protection (208)
 Glassware (204)
 Household Cleaning Agents (202)
 Skincare (202)
 Garden (192)
 Cookware & Bakeware (186)
 Luggage & Travel (185)
 Cellphones (182)
 Clothing & Footwear (182)
 Decor (182)
 Spreads, Honey & Preserves (181)
 Party Accessories (180)
 Fresh Salad, Herbs & Dip (179)
 Laundry (179)
 Sports, Nutrition & Supplements (178)
 Pens, Pencils & Markers (177)
 Soft Toys (177)
 Cooked Meats, Sandwich Fillers & Deli (175)
 Hair Accessories (173)
 Milk, Butter & Eggs (168)
 Beer (166)
 Fresh Vegetables (166)
 Magazines & Newspapers (165)
 Fragrances & Deodorant (164)
 First Aid (161)
 Bottled Water (160)
 Kitchen Disposables (159)
 Electrical (158)
 Holiday Decorations (151)
 Personal Grooming (151)
 Champagne & Sparkling Wine (150)
 Headphones & Portable Speakers (146)
 Baby Food (144)
 Kitchen Utensils, Tools & Knives (144)
 Body Wash & Shower Creams (139)
 Bread & Rolls (136)
 Building Blocks (135)
 Fresh Fruit (133)
 Smoking Accessories (133)
 Olives, Gherkins & Pickles (131)
 Baby Toiletries (130)
 Gift Bags (127)
 Hair Treatments, Serum & Oil (127)
 Kitchen Appliances (125)
 Pet Chews & Treats (124)
 Pool (121)
 Crackers & Crispbreads (120)
 Dolls (119)
 Fresh Fruit Juice (117)
 Hobbies & Crafts (116)
 Ready Meals (114)
 Toothpastes (113)
 Bathroom (112)
 Headphones & Earphones (112)
 Air Fresheners & Home Fragrance (111)
 Intimate Hygiene (110)
 Frozen Meat & Poultry (108)
 Stockings, Socks & Tights (108)
 Bar Soaps (107)
 Squash, Concentrates & Cordials (107)
 Whisky (104)
 Household Insecticides (103)
 Animal Plush Toys (99)
 Immune Support (99)
 DIY (98)
 Pencil Bags & Boxes (98)
 Shampoo (98)
 Frozen Desserts, Ice Cream & Ice (96)
 Non-Alcoholic Beverages (96)
 Desserts, Jellies & Custards (94)
 Pain Relief (93)
 Towels (93)
 Long Life Milk & Dairy Alternatives (92)
 Oils, Single Vitamins & Minerals (92)
 Cakes, Cupcakes & Tarts (91)
 Braai (89)
 Model Cars & Bikes (89)
 Rosé Wine (89)
 Decorative Storage (87)
 Frozen Fish & Seafood (87)
 Styling Products (86)
 Toothbrushes (85)
 Action Figures (84)
 Cider (84)
 General Candles (84)
 General Greeting Cards (84)
 Party Plates, Straws & Cups (83)
 Plaster, Bandages & Dressings (83)
 Nappies (82)
 Suitcases (82)
 Action Play Sets (81)
 Backpacks (80)
 Conditioner (79)
 Fancy Dress Play Sets (79)
 Heartburn & Indigestion (79)
 Liqueurs & Speciality Spirits (79)
 Flavoured Soft Drinks (78)
 Gifting Extras (78)
 Car (77)
 Constipation, Diarrhoea, IBS & Wind (75)
 Baby Milk (74)
 Computing (72)
 Face Cream & Moisturiser (72)
 Kitchen Accessories (72)
 Cake Candles (71)
 Sugar & Sweeteners (71)
 Die-Cast Toy Cars & Bikes (70)
 Home Audio & Video (70)
 Milkshakes (70)
 Sanitary Pads & Panty Liners (70)
 Character Plush Toys (69)
 Gin (68)
 Wet Cat Food (68)
 Beach & Pool (67)
 Flowers & Plants (67)
 Pool Chemicals (66)
 Multivitamins (65)
 Bedroom (64)
 Disposable Nappies (63)
 Protein Powder (63)
 Toddler Dolls (63)
 Baby Bottles (61)
 Filing & Folders (61)
 Action Figurines (60)
 Batteries (60)
 Paper (60)
 Cold & Flu (59)
 Frozen Vegetables (59)
 Board Games (58)
 Building Block Sets (58)
 Kids & Lunchbox Drinks (58)
 Polishers (57)
 Underwear & Socks (57)
 Dairy Fruit Drinks (56)
 Frozen Pizza & Garlic Bread (56)
 Mens Shaving (56)
 Milk Formula (56)
 Party Hats & Masks (56)
 Baby Lotions, Creams & Oils (55)
 Cleanser, Toner & Face Mask (55)
 Cut Flowers & Bouquets (55)
 Laundry Detergent & Fabric Softener (55)
 Party Paperware (55)
 Wet Dog Food (55)
 Dry Dog Food (54)
 Dishwashing (52)
 Drinking Yoghurt (52)
 Hair Colourants & Dyes (52)
 Cellphone Accessories & Covers (51)
 Planting Seeds (51)
 Boxed Wine (50)
 Energy Tablets, Bars & Gels (50)
 Cough Medicines (48)
 Event Greeting Cards (48)
 Gift Wrap (48)
 Outdoor Play Sets (47)
 Baby Bath & Wash (46)
 Coolers & Ice Packs (46)
 Educational Play Sets (46)
 Kitchen Towels, Cloths & Dusters (46)
 Socks (46)
 Stationery Sets (46)
 Baby & Toddler Breakfast (45)
 Brandy & Cognac (45)
 Camping (45)
 Dog Chewy Snacks (45)
 Duvet Inners, Throws & Blankets (45)
 Remote Control Cars (45)
 Wool, Sewing & Needlework (45)
 Bath Accessories (44)
 Fresh & Chilled Desserts (44)
 Mouthwash (44)
 Tissues & Toilet Rolls (43)
 Wraps, Pitas & Naan (43)
 Hand Soap & Sanitizers (42)
 Healthy Digestion Vitamins (42)
 Female Spray Deodorant (41)
 Pet Toys (41)
 Vodka (41)
 Cutting & Sticking (40)
 Baby Bottles & Cups (38)
 Binding, Laminating & Labelling (37)
 Bleach & Disinfectants (37)
 Candles (37)
 Eyecare (37)
 Face Wash & Scrub (37)
 Female Fragrances (37)
 Garden & Irrigation Accessories (37)
 Instant Cappuccino, Latte & Mocha (37)
 Puzzles (37)
 Soda & Tonic Water (37)
 Sport (37)
 Decorative Candles (36)
 Doll Play Sets (36)
 Frozen Fruit & Pastry (36)
 Pantyhose (36)
 Suncare (36)
 Video Games & Consoles (36)
 Fashion Dolls (35)
 Pre Workout & Fitness Supplements (35)
 Rooibos Tea (35)
 Globes (34)
 Cooler Bags (33)
 Energy Vitamins (33)
 Baby Toy Cars & Bikes (32)
 Dry Cat Food (32)
 Party & Entertainment Appliances (32)
 Pool Toys & Inflatables (32)
 Womens Shaving & Waxes (32)
 Antiseptics & Disinfectants (31)
 Beauty Supplements (31)
 Brooms, Brushes & Mops (31)
 Dog Biscuits (31)
 Food Preparation Appliances (31)
 Frozen Vegetarian & Meat Free (31)
 Pet Health & Hygiene (31)
 Pet Dental Chews & Bones (30)
 Umbrellas (30)
 Baby Jars (29)
 Baby Weaning (29)
 Frozen Pies & Party Food (29)
 Mageu (29)
 Muffins, Pancakes & Waffles (29)
 Trivia & Strategy Board Games (29)
 Bluetooth & Portable Speakers (28)
 Craft Beer (28)
 Dummies & Teething (28)
 Baby Wipes (27)
 Frozen Chips, Potatoes & Rice (27)
 Croissants, Scones & Pastries (26)
 Gift Boxes (26)
 Hot Drinks (26)
 Matches, Lighters & Firelighters (26)
 Tights (26)
 Collars & Leads (25)
 Cutlery (25)
 Dog Balls, Ropes & Soft Toys (25)
 Electrical Accessories (25)
 Frozen Ready Meals (25)
 Fruit & Herbal Tea (25)
 Kids Vitamins (25)
 Potting Soil, Compost & Plant Food (25)
 Stress, Relaxation & Sleep Aids (25)
 Bar Accessories (24)
 Flower & Plant Pots (24)
 From our Bakery (24)
 Outdoor Furniture (24)
 Party Toys (24)
 Tools (24)
 Baby Healthcare (23)
 Health & Beauty Appliances (23)
 Pet Pharmaceuticals (23)
 Platters & Fruit Baskets (23)
 Sports Drinks (23)
 Toy Car & Bike Play Sets (23)
 Baby Toys (22)
 Bird Food (22)
 DIY Adhesives & Fillers (22)
 Garden Insecticides (22)
 Multipack Toilet Roll (22)
 Party Decorations (22)
 Baby Dummies (21)
 Camping Chairs & Tables (21)
 First Aid Kits (21)
 Instant Coffee (21)
 Sore Throat (21)
 Tampons (21)
 Tequila (21)
 Video Game Accessories (21)
 Baby Pouches (20)
 Bins & Storage (20)
 Cleaning & Laundry Appliances (20)
 Computer Peripherals & Accessories (20)
 Fragrance Free Baby Wipes (20)
 Kids Puzzles (20)
 Reading Glasses (20)
 Underwear (20)
 Anti Dandruff & Scalp Haircare (19)
 Flavoured Water (19)
 Hot Water Bottles & Warmers (19)
 Outdoor Cookware (19)
 Rain Umbrellas (19)
 Sports Support & First Aid (19)
 Clear Skin Skincare (18)
 Correction (18)
 Electrical Adapters (18)
 Garden Tools (18)
 Hot Chocolate (18)
 Kids Juice & Smoothies (18)
 Rulers & Measuring (18)
 Baby Fruit Pots & Fruit Pouches (17)
 Beach Balls & Pool Balls (17)
 Cotton Wool & Buds (17)
 Knitting (17)
 Premix Shooters (17)
 Box Tissues (16)
 Braai Wood, Charcoal & Briquettes (16)
 Dog Collars (16)
 Female Roll-on & Stick Deodorant (16)
 Field Sports (16)
 Hard Drives & Flash Drives (16)
 Pool Cleaners & Devices (16)
 Tweezers, Nail Clippers & Grooming Accessories (16)
 Baby Bottle Teats (15)
 Birthday Decorations (15)
 Camping & Tent Accessories (15)
 Grooming (15)
 Kids & Lunchbox Juice Cartons (15)
 Kids Building Blocks (15)
 Panties (15)
 Party Packs (15)
 Portable Electronics (15)
 Repair & Restore Haircare (15)
 Soundbars & Speakers (15)
 Baby & Toddler Lunch & Dinner (14)
 Baby Shampoo & Conditioner (14)
 Boxed Fruit Juice (14)
 Doughnuts, Fresh Cookies & Iced Buns (14)
 Glucosamine & Joint Care (14)
 Heating & Cooling Appliances (14)
 Kids Haircare (14)
 Nails, Screws & Bolts (14)
 Pool Cleaning Tools & Materials (14)
 Protein Bars & Snacks (14)
 Ride-On Toys (14)
 Shoelaces (14)
 Sleep, Detox & Added Benefits Tea (14)
 Wellbeing Drinks (14)
 Baby Spoons, Bowls, Plates & Cutlery (13)
 Braai Tongs & Tools (13)
 Ceylon Tea (13)
 Energy Drinks (13)
 Lemonade & Ginger Ale (13)
 Lotion Suncare (13)
 Pet Waste Disposal (13)
 Spray Suncare (13)
 Tomato & Vegetable Juice (13)
 Baby & Toddler Snacks (12)
 Cat Litter & Litter Boxes (12)
 Dry and Irritated Skincare (12)
 Footwear (12)
 Handbags (12)
 Male Fragrances (12)
 Mens Vitamins (12)
 Pet Bowls (12)
 Playing Cards & Card Games (12)
 Protein Drinks (12)
 Sewing & Needlework (12)
 Slippers (12)
 TVs (12)
 Braai Accessories (11)
 Camping Lights (11)
 Coffee Pods (11)
 Eye Drops & Rinses (11)
 Face Wipes (11)
 Hair Removal Creams & Sprays (11)
 Hayfever & Allergy (11)
 Keyboards & Mice (11)
 Nicotine Replacement (11)
 Potted Plants (11)
 Powerbanks & Portable Chargers (11)
 Scourers & Steel Wool (11)
 Sim Cards (11)
 Streamers & Confetti (11)
 Baby Powder (10)
 Boxers & Briefs (10)
 Fresh Fish & Seafood (10)
 Gas Cookers (10)
 Green Tea (10)
 Paint & Accessories (10)
 Ready To Drink Baby Milk (10)
 Stout (10)
 Womens Vitamins (10)
 Adult Puzzles (9)
 Audio & Video Cabling & Connectors (9)
 Bath & Toilet Mats (9)
 Buckets & Basins (9)
 Cat Snacks & Treats (9)
 Dental Flosses (9)
 Fresh Smoothies (9)
 Pool Accessories (9)
 Potty Training & Pull Up Nappies (9)
 Premix Cocktails & Cocktail Ingredients (9)
 Age 50+ Vitamins (8)
 Audio & Video Components (8)
 Baby Bath Toys (8)
 Baby Rattles (8)
 Beach Umbrellas (8)
 Conception & Pregnancy Vitamins (8)
 Electric Shavers, Waxers & Groomers (8)
 Extension Cords (8)
 Kids Beach Toys & Buckets (8)
 Makeup (8)
 Mixed Platters (8)
 Nails (8)
 Pesticides (8)
 Pet Shampoo & Conditioner (8)
 Push Cars & Bikes (8)
 Security (8)
 Specialist Baby Milk & Formula (8)
 Torches & Lanterns (8)
 Traditional Braais (8)
 Travel Accessories (8)
 Adult Diapers & Protection (7)
 Anti Wrinkle Skincare (7)
 Baby Bibs & Burp Cloths (7)
 Baby Cups & Beakers (7)
 Baby Teething (7)
 Camping Tools (7)
 Cat Collars (7)
 Cleaning Protection & Wear (7)
 Colic Relief & Gripe Water (7)
 Foot Care (7)
 Male Spray Deodorant (7)
 Modems, Routers & Networking (7)
 Non-Alcoholic Beer (7)
 Rum (7)
 Swimming (7)
 Swimming Goggles (7)
 We Want You To Save (7)
 Animal & Wildlife Figurines (6)
 Baby Cough, Cold & Congestion (6)
 Baby Juice (6)
 Bathroom Accessories (6)
 Car Cleaning & Sun Care (6)
 Cast Iron Pots & Potjies (6)
 Cat Toys & Catnip (6)
 Cocktail & Cheese Platters (6)
 Computer Headphones & Headsets (6)
 Contact Lenses & Care (6)
 Cooler Boxes (6)
 Court Sports (6)
 Denture Care (6)
 Dog & Cat Plushies (6)
 Dry Shampoo (6)
 Facial Suncare (6)
 Kids Medicines (6)
 Laundry Bins & Baskets (6)
 Nappy Sacks & Bins (6)
 Nursery (6)
 Nursery Linen & Bedding (6)
 Pet Brushes & Combs (6)
 Pool Pumps & Fittings (6)
 Portable Pools (6)
 Stainless Steel Pet Bowls (6)
 Still Water (6)
 Vases (6)
 Video Game Consoles (6)
 Adult Clothing (5)
 Baby Bottle Brushes (5)
 Baby Pain & Temperature Relief (5)
 Braai Grids (5)
 Breast Feeding (5)
 Cola (5)
 Diet & Sugar Free Soft Drinks (5)
 Earl Grey Tea (5)
 Flavoured Syrups (5)
 Fragranced Baby Wipes (5)
 Fruit Concentrates (5)
 Home Audio & Entertainment Systems (5)
 Iced Coffee (5)
 Interactive Dolls (5)
 Kids & Lunchbox Drink Pouches (5)
 Kids Board Games (5)
 Kids Camping (5)
 Kids Tablets (5)
 Lawnmowers & Trimmers (5)
 Meat Platters (5)
 Mobile Audio Cables & Connectors (5)
 Nebulizers & Humidifiers (5)
 Non-Alcoholic Ciders (5)
 Sherry & Port (5)
 Sleeping Bags, Stretchers & Mattresses (5)
 Spirits & Liqueurs Gifts (5)
 Sterilising & Antibacterial (5)
 Tops, Shirts & T-Shirts (5)
 TV Accessories (5)
 Bathroom Fittings (4)
 Beard Grooming (4)
 Bouncing Toys (4)
 Braai Cleaning (4)
 Compact Umbrellas (4)
 Doll Accessories (4)
 Eco-Friendly (4)
 Eco-Friendly Cleaning (4)
 Expecting Mothers (4)
 Fish Food (4)
 Professional Dental (4)
 Hand Gel & Wipes (4)
 Ice Packs (4)
 Iced Tea (4)
 Interactive Plush Toys (4)
 Kettle Braais (4)
 Kids Suncare (4)
 Lighting (4)
 Malted Hot Drinks (4)
 Natural Haircare (4)
 Pet Bedding & Comfort (4)
 Pet Odour & Stain Eliminators (4)
 Pet Vitamins (4)
 Plastic Pet Bowls (4)
 Rodent Food (4)
 Rope, Chains & Twine (4)
 Soccer (4)
 Soda Water (4)
 Sterilising Fluid & Tablets (4)
 Tablets (4)
 Tonic Water (4)
 Adult Tents (3)
 Baby Clothing & Footwear (3)
 Battery Cables & Chargers (3)
 Bicycles (3)
 Coconut Water & Aloe Juice (3)
 Colour Haircare (3)
 Cordials (3)
 Dice Games (3)
 Digital Satellite Decoders, Dishes & Accessories (3)
 Exercise Equipment (3)
 Fittings & Shelving (3)
 Frisbees & Throwing Toys (3)
 Fruit Squash (3)
 General Pet Toys (3)
 Gym, Health & Fitness (3)
 Holiday Greeting Cards (3)
 Kids Pools (3)
 Laptop & Notebook Computers (3)
 Male Roll-on & Stick Deodorant (3)
 Ornaments (3)
 Pet Cushions & Blankets (3)
 Picnic Bags (3)
 Professional Haircare (3)
 Radios & Alarm Clocks (3)
 Single Toilet Roll (3)
 Sport & Travel Bags (3)
 Static Figurines (3)
 Swim Nappies (3)
 Tableware (3)
 Adult Socks (2)
 Artificial Plants & Flowers (2)
 Baby Activity Toys (2)
 Baby Building Blocks (2)
 Baby Caps, Mittens & Scarfs (2)
 Baby Cotton Wool, Buds & Sponges (2)
 Baby Food Storage, Weaning Pots & Trays (2)
 Baby Scissors, Nail Clippers & Combs (2)
 Battery & Electric Toothbrushes (2)
 Breast Pads (2)
 Calculators (2)
 Camping Backpacks & Rucksacks (2)
 Chicken & Poultry Platters (2)
 Compact Outdoor Cookware (2)
 Computer Monitors (2)
 Curtains Rails & Blinds (2)
 Dog & Cat Dental Toys (2)
 Dog Leads (2)
 Educational Baby Toys (2)
 Electronic Scales (2)
 Flavoured Hot Drinks (2)
 Fruit & Vegetable Platters (2)
 Heart Health Vitamins (2)
 Hospital Essentials (2)
 Jugs & Water Carriers (2)
 Kids & Lunchbox Drink Bottles (2)
 Kids Bicycles (2)
 Kids Oral Care (2)
 Makeup & Nails (2)
 Nappy Cream (2)
 Nipple Cream (2)
 Non-Alcoholic Spirit Coolers (2)
 Patio Accessories (2)
 Pet Training (2)
 Pocket Tissues (2)
 Protein Shakers & Accessories (2)
 Protein Shakes (2)
 Sambuca (2)
 Sensitive Oral Care (2)
 Sparkling Water (2)
 Teething (2)
 Tennis (2)
 Water Canisters & Bottles (2)
 Whitening Oral Care (2)
 Wine Gift Sets (2)
 Advanced Building Blocks (1)
 Antibacterial Baby Spray (1)
 Baby & Toddler Dessert (1)
 Baby Bottle Preparation (1)
 Baby Furniture & Travel (1)
 Baby Maternity Accessories (1)
 Baby Seats & Chairs (1)
 Baby Toothbrush & Toothpaste (1)
 Baby Travel Toys & Mobiles (1)
 Baby Vitamins (1)
 Basketball (1)
 Bedwetting & Dry Nites (1)
 Bluetooth Audio Transmitters & Receivers (1)
 Body Lotion, Moisturiser & Scrub (1)
 Braai Gloves & Protection (1)
 Breast Milk Storage (1)
 Burn Treatments (1)
 Camera (1)
 Camping Showers & Accessories (1)
 Camping Stretchers & Cupboards (1)
 Clothing Pegs & Clips (1)
 Coffee Beans (1)
 Coffee Filters (1)
 Cosmetic Accessories (1)
 Cutting & Measuring (1)
 De-Shedding Tools & Scissors (1)
 Decaf Tea (1)
 Disc & Media Players (1)
 Floorcare Appliances (1)
 Food & Water Dispenser Accessories (1)
 Food & Water Dispensers (1)
 Fortified Wine & Vermouth (1)
 Garden Decor (1)
 Gas Braais (1)
 General Decorations (1)
 Hangers (1)
 Hoses, Sprinklers & Watering Cans (1)
 Kennels & Carriers (1)
 Kids Tents (1)
 Laptop & Notebook Accessories (1)
 Lip Balm, Ulcer & Cold Sore Relief (1)
 Lipstick & Gloss (1)
 Loose Leaf Tea (1)
 Luxury & Foam Sided Pet Beds (1)
 Mobile Routers (1)
 Newborn Essentials (1)
 Non-Alcoholic Wine (1)
 Outdoor Cookware Sets (1)
 Pet Bowl Sets (1)
 Pet Carriers & Bags (1)
 Pet Litter Scoops (1)
 Pet Potty Training (1)
 Pet Training Devices (1)
 Pillar Candles (1)
 Pregnancy Creams & Lotion (1)
 Punches & Staplers (1)
 Refuse Bags & Bin Liners (1)
 Rubix Cubes & Mind Puzzles (1)
 Slot Cars (1)
 Special Plants (1)
 Storage (1)
 Tablet Accessories & Covers (1)
 Thermometers (1)
 White Hot Chocolate (1)
 White Tea